# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be8fbd46789e733020c3ec9f207d51bc"
name = "shop_cloud"
api_version = "2026-01"
application_url = "https://cloudflare-workers-app.radhouenekhalfa.workers.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_app_proxy,read_customers,read_discounts,read_inventory,read_locations,read_metaobjects,read_orders,read_price_rules,read_products,write_app_proxy,write_customers,write_discounts,write_metaobjects,write_orders,write_price_rules,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://cloudflare-workers-app.radhouenekhalfa.workers.dev/api/auth",
  "https://cloudflare-workers-app.radhouenekhalfa.workers.dev/auth/callback"
]

[app_proxy]
url = "https://cloudflare-workers-app.radhouenekhalfa.workers.dev/proxy"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = true
